"""Retry decorator constants."""

from mixin_retry.decorators.constants.retried import (
    ATTRIBUTE_MARKER,
    ATTRIBUTE_MAX_ATTEMPTS,
    BASE_DELAY_DEFAULT,
    ERROR_MSG_INVALID_PREDICATE,
    ERROR_MSG_MAX_ATTEMPTS_INVALID,
    ERROR_MSG_TARGET_NOT_CLASS_OR_CALLABLE,
    JITTER_DEFAULT,
    MAX_DELAY_DEFAULT,
)

__all__ = [
    "ATTRIBUTE_MARKER",
    "ATTRIBUTE_MAX_ATTEMPTS",
    "BASE_DELAY_DEFAULT",
    "ERROR_MSG_INVALID_PREDICATE",
    "ERROR_MSG_MAX_ATTEMPTS_INVALID",
    "ERROR_MSG_TARGET_NOT_CLASS_OR_CALLABLE",
    "JITTER_DEFAULT",
    "MAX_DELAY_DEFAULT",
]
